name: deploy website to s3
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      
      - name: checkout code
        uses: actions/checkout@v4
      # 5. Configure AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
      - name: deploy to s3
        run: |
          aws s3 create-bucket shoukat-portfoliio-1 --region us-east-1
